### ISSUE TITLE
pass PR number dynamically

### ISSUE THREAD

**Issue by nakamasato** [nakamasato/github-actions-practice#3]
pass PR number dynamically, otherwise useless

```
    - name: Merge Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        number: 2
```
