### ISSUE TITLE
docker cache comparison

### ISSUE THREAD

**Issue by nakamasato** [nakamasato/github-actions-practice#377]
## inline

(skip) as registry covers everything that inline cache can do

## registry

```yaml
      - name: Build with registry cache
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: push
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mysql-operator:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mysql-operator:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/mysql-operator:buildcache
```
## github actions 
```yaml
      - name: Build with github actions cache
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: push
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mysql-operator:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
```

## local

https://docs.docker.com/build/ci/github-actions/cache/#local-cache
